#!/usr/bin/env node
/* ==========================================================================
   Layered by Light — site builder
   --------------------------------------------------------------------------
   Reads   data/products.json          (the source of truth — edit this)
   Writes  data/products.js            (browser-readable copy; works offline)
           products/<slug>.html        (one real page per product, for Google)

   Run it after any change to products.json:

       node scripts/build.js

   No dependencies, no npm install needed.
   ========================================================================== */
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const dataFile = path.join(root, 'data', 'products.json');
const templateFile = path.join(root, 'templates', 'product.template.html');
const productsDir = path.join(root, 'products');

function fail(message) {
  console.error('\n  Build failed: ' + message + '\n');
  process.exit(1);
}

/* --- load and check ------------------------------------------------------ */

if (!fs.existsSync(dataFile)) fail('data/products.json not found.');
if (!fs.existsSync(templateFile)) fail('templates/product.template.html not found.');

let data;
try {
  data = JSON.parse(fs.readFileSync(dataFile, 'utf8'));
} catch (err) {
  fail('data/products.json is not valid JSON — ' + err.message);
}

const problems = [];
const seenSlugs = new Set();
const seenIds = new Set();
const categoryIds = new Set((data.categories || []).map(c => c.id));

(data.products || []).forEach((p, i) => {
  const where = 'product ' + (i + 1) + ' (' + (p.name || 'unnamed') + ')';
  if (!p.id) problems.push(where + ' has no "id".');
  if (!p.slug) problems.push(where + ' has no "slug".');
  if (!p.name) problems.push(where + ' has no "name".');
  if (typeof p.price !== 'number') problems.push(where + ' needs a numeric "price".');
  if (p.category && !categoryIds.has(p.category)) problems.push(where + ' uses category "' + p.category + '" which is not in "categories".');
  if (seenIds.has(p.id)) problems.push('Duplicate id "' + p.id + '".');
  if (seenSlugs.has(p.slug)) problems.push('Duplicate slug "' + p.slug + '".');
  seenIds.add(p.id);
  seenSlugs.add(p.slug);
  (p.options || []).forEach(opt => {
    if (!opt.id) problems.push(where + ' has an option with no "id".');
    if (!opt.label) problems.push(where + ' option "' + opt.id + '" has no "label".');
    if (opt.type === 'select' && !(opt.choices || []).length) {
      problems.push(where + ' option "' + opt.id + '" is a select with no choices.');
    }
  });
});

if (problems.length) {
  console.error('\n  Problems in data/products.json:');
  problems.forEach(p => console.error('    - ' + p));
  fail(problems.length + ' problem(s) found. Nothing was written.');
}

/* --- write the browser data file ----------------------------------------- */

const jsBanner = '/* GENERATED by scripts/build.js — do not edit.\n' +
                 '   Edit data/products.json, then run: node scripts/build.js */\n';
fs.writeFileSync(
  path.join(root, 'data', 'products.js'),
  jsBanner + 'window.LBL_PRODUCTS = ' + JSON.stringify(data, null, 2) + ';\n',
  'utf8'
);

/* --- write one page per product ------------------------------------------ */

const template = fs.readFileSync(templateFile, 'utf8');

function escapeHtml(value) {
  return String(value == null ? '' : value)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function categoryName(id) {
  const found = (data.categories || []).find(c => c.id === id);
  return found ? found.name : '';
}

if (!fs.existsSync(productsDir)) fs.mkdirSync(productsDir, { recursive: true });

// Remove pages for products that no longer exist, so deleted products vanish.
const validPages = new Set((data.products || []).map(p => p.slug + '.html'));
fs.readdirSync(productsDir)
  .filter(f => f.endsWith('.html') && !validPages.has(f))
  .forEach(f => {
    fs.unlinkSync(path.join(productsDir, f));
    console.log('  removed  products/' + f + '  (no longer in products.json)');
  });

(data.products || []).forEach(product => {
  const values = {
    NAME: escapeHtml(product.name),
    SHORT_DESCRIPTION: escapeHtml(product.shortDescription || ''),
    DESCRIPTION: escapeHtml(product.description || product.shortDescription || ''),
    PRICE: '$' + Number(product.price).toFixed(2),
    LEAD_TIME: escapeHtml(product.leadTime || ''),
    PRODUCT_ID: escapeHtml(product.id),
    CATEGORY_NAME: escapeHtml(categoryName(product.category)),
    IMAGE: escapeHtml((product.images && product.images[0]) || 'assets/images/products/placeholder-lightbox.svg')
  };

  const html = template.replace(/\{\{(\w+)\}\}/g, (match, key) =>
    Object.prototype.hasOwnProperty.call(values, key) ? values[key] : match
  );

  fs.writeFileSync(path.join(productsDir, product.slug + '.html'), html, 'utf8');
  console.log('  built    products/' + product.slug + '.html');
});

console.log('\n  Done. ' + (data.products || []).length + ' product page(s) and data/products.js written.\n');
